### ISSUE TITLE
Will not schedule at all

### ISSUE THREAD

**Issue by Nokel81** [node-schedule/node-schedule#243] opened 2016-02-01 20:24 UTC
Having this code is test.js

`var schedule = require('node-schedule');

var j = schedule.scheduleJob('*/10 * * * *', function () {
    console.log(Date());
});`

Then it prints the date immediately and the program stops. The program is run by using the command:
node test.js

**Comment by santigimeno** [comment] 2016-02-01 20:48
Probably a duplicate of https://github.com/node-schedule/node-schedule/issues/236. Can you check that issue?

**Comment by santigimeno** [comment] 2016-02-01 21:01
Fixed in 2468fb7 and released as version 1.0.0.
Major props to @albertdatui for the excellent fix.

**Closed by santigimeno** 2016-02-01 21:01 UTC
