### ISSUE TITLE
【Bug】schedule.scheduleJob executed twice

### ISSUE THREAD

**Issue by HuMoran** [node-schedule/node-schedule#471] opened 2018-11-09 02:39 UTC
AWS Ubuntu 16.04.4 LTS (GNU/Linux 4.4.0-116-generic x86_64)
node: v8.11.1
node-schedule:  1.2.4

my code：
```js
// Everyday 0:00, generater new tasks
const rule = new schedule.RecurrenceRule();
rule.hour = 0;
rule.minute = 0;
rule.second = 0;
schedule.scheduleJob(rule, () => {
  console.log('Recurrence job start');
  getTaskRules();
});
```
my log:
![image](https://user-images.githubusercontent.com/25628402/48239266-3af87480-e409-11e8-83f7-8122022ee51b.png)
![image](https://user-images.githubusercontent.com/25628402/48239345-798e2f00-e409-11e8-93e6-3dfc7df8f217.png)
![image](https://user-images.githubusercontent.com/25628402/48239376-99255780-e409-11e8-834f-84ead195197b.png)
Previous log is ok too!
![image](https://user-images.githubusercontent.com/25628402/48239431-cffb6d80-e409-11e8-94c5-0d0bd6c9f2f3.png)
server no restart,  no error:
![image](https://user-images.githubusercontent.com/25628402/48239641-9ecf6d00-e40a-11e8-96d6-f798d7bb7007.png)

I have encountered this problem a few months ago, I just restarted the server, it works fine!
but now，it is coming again!

**Comment by HuMoran** [comment] 2018-11-09 02:42
I am not good at English……

**Comment by mreis1** [comment] 2018-11-20 13:21
I'm having the same problem. 

![image](https://user-images.githubusercontent.com/1719667/48776214-847d7500-eccf-11e8-8017-731efcfd241e.png)

Here's the code:

```
let time = [
            '0'/*seconds*/,
            '0,5,10,15,20,25,30,35,40,45,50,55'/*min*/,
            '*'/*hours*/,
            '*'/*days*/,
            '*'/*month*/,
            '*'/*day of week*/
        ].join(' '); // every minute multiple of 5

        this.cron = scheduleJob(time, async () => {
            try {
                DebugHub.ReaderEvents('Running cron');
                await AccessControlModule.accessControlValidationResultEventManager.verifyConnection()
            } catch (err) {
                Logger.error(err);
            }
            try {
                await AccessControlModule.cardEventManager.verifyConnection()
            } catch (err) {
                Logger.error(err);
            }
        });
```

**Comment by mreis1** [comment] 2018-11-21 08:17
Also affects versions 1.3.0.
Tested on both, mac os and windows 10.

**Comment by HuMoran** [comment] 2018-11-26 09:22
> Also affects versions 1.3.0.
> Tested on both, mac os and windows 10.

no one helps us

**Comment by santigimeno** [comment] 2018-11-26 09:31
@HuMoran there was an issue fixed in `1.3.0`. Can you check if using `1.3.0` works for your case?

In the meantime I'll look into @mreis1 issue

**Comment by santigimeno** [comment] 2018-11-26 09:32
@mreis1 how long does it take before it starts failing?

**Comment by HuMoran** [comment] 2018-11-26 10:42
@santigimeno ok，let me try 1.3.0. But it needs a long time can be verified

**Comment by mreis1** [comment] 2018-11-26 12:43
@santigimeno it starts on the first run.

**Comment by santigimeno** [comment] 2018-11-26 13:56
I'm using this code: 
```js
const { scheduleJob } = require('node-schedule');

let time = [
    '0'/*seconds*/,
    '0,5,10,15,20,25,30,35,40,45,50,55'/*min*/,
    '*'/*hours*/,
    '*'/*days*/,
    '*'/*month*/,
    '*'/*day of week*/
].join(' '); // every minute multiple of 5

let i = 0;
const cron = scheduleJob(time, async () => {
    console.log(`[${++i}] ${new Date()}`);
});
```

and works correctly :man_shrugging:

**Comment by mreis1** [comment] 2018-11-26 16:43
I didn't perform an isolated test but I have multiple cron jobs running in the process. 
Some of the cron jobs have different intervals.

**Comment by santigimeno** [comment] 2018-11-26 17:07
I get it. I would need a reproducible test case in order to track this.

**Comment by mreis1** [comment] 2018-11-27 21:38
@santigimeno I'll see If i can provide you with an example.

**Comment by mreis1** [comment] 2018-12-03 12:44
I think the issue is not related with node-schedule itself. 
In my project I use node-graceful to perform some operations when a kill signal is received.  While I were able to ctrl+c and start the app again, the process was still alive and as consequence If i started the program again, I would see console.logs coming from the process that was not yet dead. 

I'll check this to be sure that I'm not misunderstanding what was going on. 👍

**Comment by yousefissa** [comment] 2019-01-13 21:19
Any fix on this? I'm having my scheduler run multiple times. Using express and react, so could it have something to do with the multiple node processes running?

**Comment by mreis1** [comment] 2019-04-09 08:52
@yousefissa there's an easy way to determine this. 
If you run `killall -9 node` all node apps will die. 
There you can start your app again. If you see double treatment the issue might be other than multiple processes "console.logging" to the same stdout (in my case the same window console).

**Comment by harae** [comment] 2019-05-30 09:23
Has this problem been solved?

**Comment by HuMoran** [comment] 2019-05-31 02:20
I update to  1.3.0 and it had worked fine for a few months.

**Closed** 2019-05-31 02:21 UTC

**Comment by linkFly6** [comment] 2020-01-19 09:37
If you used PM2, because PM2 is used to start two processes。

![image](https://user-images.githubusercontent.com/6982402/72678598-56b5db00-3ae2-11ea-80c5-a403918ea56b.png)

**Comment by Fauzdar1** [comment] 2021-09-15 05:58
Same issue, `schedule.scheduleJob` with a date executes twice at the same time.

```
schedule.scheduleJob(date, () => {
    console.log(data);
});
```

**Comment by emran-jatri** [comment] 2022-11-29 11:30
> 

I'm using pm2 and facing schedule.scheduleJob runs twice, so what should I do for run it single time.

**Comment by emran-jatri** [comment] 2022-11-29 11:31
> If you used PM2, because PM2 is used to start two processes。
> 
> ![image](https://user-images.githubusercontent.com/6982402/72678598-56b5db00-3ae2-11ea-80c5-a403918ea56b.png)

I'm using pm2 and facing schedule.scheduleJob runs twice, so what should I do for run it single time.

**Comment by pedrobrochero** [comment] 2023-03-07 15:59
Haven't tested yet but apparently this is the fix:

https://github.com/node-schedule/node-schedule/issues/263#issuecomment-218387587

**Comment by Bek81** [comment] 2023-09-06 08:53
> > If you used PM2, because PM2 is used to start two processes。
> > ![image](https://user-images.githubusercontent.com/6982402/72678598-56b5db00-3ae2-11ea-80c5-a403918ea56b.png)
> 
> I'm using pm2 and facing schedule.scheduleJob runs twice, so what should I do for run it single time.

I'm using pm2, but not in cluster mode. So it's an anomaly.
