### ISSUE TITLE
Schedule only firing on app start

### ISSUE THREAD

**Issue by toymachiner62** [node-schedule/node-schedule#489] opened 2019-03-27 23:00 UTC
I have 2 files, `index.js` and `scheduler.js`.

index.js
```js
const scheduler = require('./scheduler')

console.log('starting')
scheduler()
```

scheduler.js
```js
const schedule = require('node-schedule')

function scheduler () {
  schedule.scheduleJob('*/1 * * * *', doStuff())
}

function doStuff () {
  console.log('in doStuff. The time is ', new Date())
}

module.exports = scheduler
```

According to `https://crontab.guru/#*/1_*_*_*_*` my cron syntax should fire every minute, but it is only firing on app start and then errors the next minute when it tries to fire.

```sh
 npm start

> schedule@1.0.0 start /Users/tomcaflisch/Sites/schedule
> node index.js

starting
in doStuff. My dogs name is foo. The time is  2019-03-27T23:39:16.218Z
/Users/tomcaflisch/Sites/schedule/node_modules/node-schedule/lib/schedule.js:175
    this.job.execute(fireDate);
             ^

TypeError: Cannot read property 'execute' of undefined
    at Job.invoke (/Users/tomcaflisch/Sites/schedule/node_modules/node-schedule/lib/schedule.js:175:14)
    at /Users/tomcaflisch/Sites/schedule/node_modules/node-schedule/lib/schedule.js:552:11
    at Timeout._onTimeout (/Users/tomcaflisch/Sites/schedule/node_modules/node-schedule/lib/schedule.js:510:7)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! schedule@1.0.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the schedule@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/tomcaflisch/.npm/_logs/2019-03-27T23_40_00_012Z-debug.log
```
Seems that if i don't pass in a parameter and call `schedule.scheduleJob('*/1 * * * *', doStuff)` instead of `schedule.scheduleJob('*/1 * * * *', doStuff())` it works just fine. 

Is there any way to pass in a function in which I pass in params as the callback in the `scheduleJob` function?

**Comment by Favna** [comment] 2019-04-01 09:49
Why even separate the callback function? Just do it like this:

```js
// index.js
const scheduler = require('./scheduler')

console.log('starting')
scheduler('awesome arg')
```

```js
// scheduler.js
const schedule = require('node-schedule')

function scheduler (arg) {
  schedule.scheduleJob('*/1 * * * *', function () {
      console.log('in doStuff. The time is', new Date());
      console.log('And your arg was: ', arg);
  })
}

module.exports = scheduler
```

Or even shorter with ES6 modules, arrow functions, and template literals:

```js
import scheduler from './scheduler';

console.log('starting')
scheduler('awesome arg')
```

```js
import { scheduleJob } from 'node-schedule';

export default (arg) => {
    scheduleJob('*/1 * * * *', () => {
        console.log(`in doStuff. The time is: ${new Date()}`);
        console.log(`And your arg was: ${arg}`);
    });
}
```

**Comment by toymachiner62** [comment] 2019-04-01 16:04
3 reasons:
1) B/c my code can't be modular if i follow your suggestion. 

The functions that I'm putting on a schedule with node-schedule I also want to execute via a REST endpoint

2) I want to be able to write unit tests for my functions. By embedding them inside `schedule.scheduleJob` It makes it much harder to unit test just the logic

3) I plan to schedule many jobs (say 100). I don't want all those functions in a single file that's 5K lines long.

**Comment by MathieuAA** [comment] 2019-04-02 13:53
@toymachiner62 the issue is that the code from your scheduler is wrong, it should be:
```javascript
const schedule = require('node-schedule')

function scheduler () {
  schedule.scheduleJob('*/1 * * * *', doStuff) // <-- here
}

function doStuff () {
  console.log('in doStuff. The time is ', new Date())
}

module.exports = scheduler
```

You were passing `undefined` in your example instead of a function.

**Comment by toymachiner62** [comment] 2019-04-15 15:17
@MathieuAA How do you figure? I just didn't include the implementation of `doStuff` in my sample code above.

**Comment by MathieuAA** [comment] 2019-04-16 09:39
I didn't need the implem :) I just figured that the scheduleJob function takes a function, not what the doStuff function might return.

**Comment by MathieuAA** [comment] 2019-04-16 11:00
That, and I guessed that your doStuff function returned nothing.

**Comment by toymachiner62** [comment] 2019-04-16 12:56
`doStuff` doesn't return anything. It's simply a function which executes some code. It shouldn't need to return anything should it?

**Comment by MathieuAA** [comment] 2019-04-16 15:45
Absolutely not, that's up to you anyway. Anyway, I guess you can close this issue now :)

**Closed** 2019-04-16 15:58 UTC
