### ISSUE TITLE
How would I guarantee "everyday at UTC midnight"?

### ISSUE THREAD

**Issue by InstanceOfMichael** [node-schedule/node-schedule#222] opened 2015-12-23 17:13 UTC
related to: https://github.com/node-schedule/node-schedule/issues/217

 - If I present a ``new Date``, it looks like I can't make it daily recurring.
 - If I use ``moment-timezone``, I'm not sure what timezone node-schedule is using for any given potential server.

```
var job = schedule.scheduleJob('00 00 * * *', function(){});
```

I haven't verified that this doesn't work.

**Comment by tejasmanohar** [comment] 2015-12-23 22:24
node-timezone uses system time as it stands. as it stands, you may be able to get the current timezone and then use moment-timezone to manipulate the rules accordingly before passing it to `scheduleJob`... haven't worked out all the logic for that yet but the offset getter should help. this is a feature request though; see #217

**Comment by kinduff** [comment] 2016-01-18 00:48
Not sure if related and didn't want to open a new issue. I'm passing a date with `new Date` but i'm in `GMT-0600 (CST)` the tasks don't seem to be scheduled, am I missing something? Also tried using the `Date.UTC` method.

**Comment by tejasmanohar** [comment] 2016-02-01 08:05
dupe of #217

**Closed by tejasmanohar** 2016-02-01 08:05 UTC
