### ISSUE TITLE
Jobs don't fire due to leap year

### ISSUE THREAD

**Issue by albertdatui** [node-schedule/node-schedule#225] opened 2016-01-08 06:39 UTC
There is a bug in cron-parser library.
I suspect that it is due to the leap year.

Here is the snippet of the error code.

![screen shot 2016-01-08 at 2 37 46 pm](https://cloud.githubusercontent.com/assets/5680331/12191992/930c222c-b615-11e5-9365-36dce04278ef.png)

**Comment by santigimeno** [comment] 2016-01-08 09:20
I can confirm these errors are happening. Will look into them. Thanks for reporting!

**Comment by JosMarRivera** [comment] 2016-01-28 12:38
+1

**Comment by fenwick67** [comment] 2016-01-29 00:22
This bit me today.

This may be a duplicate of #172.

**Comment by JamCode** [comment] 2016-01-29 09:17
![image](https://cloud.githubusercontent.com/assets/3069764/12671644/0ff5e4ca-c6ac-11e5-9255-8411000900d0.png)

+1

**Comment by zaikin-andrew** [comment] 2016-01-29 16:51
+1 
![image](https://cloud.githubusercontent.com/assets/7475399/12681854/aa07b6fa-c6c1-11e5-8689-fb47e7406b10.png)

**Comment by ericsandine** [comment] 2016-01-29 19:47
:+1: 
![screenshot 2016-01-29 11 45 46](https://cloud.githubusercontent.com/assets/4127135/12686321/e8be18a6-c67d-11e5-86b7-f673dc875956.png)

`var time = '00 41 11 * * 1-5';`

**Comment by santigimeno** [comment] 2016-01-30 16:20
Hey guys, can you check if the changes in https://github.com/node-schedule/node-schedule/pull/233 fix the issue for you? Thanks!

**Comment by adityabansod** [comment] 2016-01-31 16:39
:+1:

**Comment by corbanb** [comment] 2016-01-31 17:30
IS there a fix for today then? I updated to 0.6.0.

**Comment by GermanBluefox** [comment] 2016-01-31 17:43
I use node-schedule in my project. It is about 1000 people who use it. They all can't control heating, light and so on. I am interesting in solution too.

**Comment by tejasmanohar** [comment] 2016-01-31 17:44
https://github.com/node-schedule/node-schedule/pull/233#issuecomment-177562982

**Comment by santigimeno** [comment] 2016-01-31 18:34
Hi all. I understand this issue is important for all. I plan releasing a `1.0.0` release soon (soon meaning when I/we can). In the meantime, it would really help if you could try the great fix from @albertdatui in https://github.com/node-schedule/node-schedule/pull/233 and provide feedback. Also, as @tejasmanohar said here https://github.com/node-schedule/node-schedule/pull/233#issuecomment-177562982, you can always add the branch from @albertdatui to your `package.json` to include the fix in your project. Thanks

**Comment by fenwick67** [comment] 2016-01-31 19:00
I'm trying out the @albertdatui branch... it seems to be working for me.

**Comment by KevinC0** [comment] 2016-02-01 00:00
@albertdatui branch is also working properly for me. In package.json: `"node-schedule": "git://github.com/albertdatui/node-schedule.git#bugFixLeapYear"`

**Comment by wwgc** [comment] 2016-02-01 02:51
+1

**Comment by nmors** [comment] 2016-02-01 03:17
+1

**Comment by vwatson** [comment] 2016-02-01 06:48
+1

**Comment by ivands** [comment] 2016-02-01 07:39
+1
i'm getting this error once a day.
Please fix this.
It's unusable right now.

**Comment by tejasmanohar** [comment] 2016-02-01 08:04
this is a semver major change. @santigimeno suggests grouping it w/ the other 1.0 changes, which I stand by. in the meantime, see-
- https://github.com/node-schedule/node-schedule/issues/225#issuecomment-177664035
- https://github.com/node-schedule/node-schedule/pull/233#issuecomment-177562982
*and definitely do not comment here or open additional issues unless you've read the above*

**Comment by holm** [comment] 2016-02-01 08:06
I deployed the branch from the pull request last night, and while there are no errors now, it also doesn't seem like it is firing any crons now.

**Comment by tejasmanohar** [comment] 2016-02-01 08:26
@holm Can you provide an example we can run to replicate? Maybe you can use sinon fake timers to tests this? Small, isolated- separate from all your business logic and so forth.

**Comment by holm** [comment] 2016-02-01 08:29
Absolutely. Let me look into a bit more and see what I can find and come up with a testcase.

**Comment by tejasmanohar** [comment] 2016-02-01 08:32
Thanks! Next few days are super busy :sweat: so no promises, but a reproducible test case makes debugging this 100x easier (and more reasonable) for anyone who'd like to attempt it.

**Comment by mefernandez** [comment] 2016-02-01 08:42
Hi,

Same problem here, cron broke down tonight.

Code:
```js
schedule.scheduleJob('*/1 * * * *', function(){
```

Last successful log date:
```
Sun, 31 Jan 2016 23:58:00
```

**Comment by santigimeno** [comment] 2016-02-01 09:06
@mefernandez Is that failing even after applying the changes from https://github.com/node-schedule/node-schedule/pull/233

**Comment by mefernandez** [comment] 2016-02-01 09:14
@santigimeno Did not apply changes from #233 yet.
I see it's still an open PR, any advice on how to apply those changes?

**Comment by doronMendelson** [comment] 2016-02-01 09:16
My job just fails when I use * * * * *

**Comment by santigimeno** [comment] 2016-02-01 09:16
@mefernandez this: https://github.com/node-schedule/node-schedule/issues/225#issuecomment-177664035

**Comment by santigimeno** [comment] 2016-02-01 09:17
@doronMendelson Have you read this: https://github.com/node-schedule/node-schedule/issues/225#issuecomment-177831888 ?

**Comment by mefernandez** [comment] 2016-02-01 09:36
@santigimeno @doronMendelson I see, thanks.

**Comment by doronMendelson** [comment] 2016-02-01 09:42
I saw the comment and tried it, but it still fails

**Comment by santigimeno** [comment] 2016-02-01 10:01
@doronMendelson How does it fail? I've just tried this:
```
var schedule = require('./');

schedule.scheduleJob('* * * * *', function() {
  console.log('Fired: ' + new Date());
});
```
And the output shows that the job fires every minute which is to be expected:
```
Fired: Mon Feb 01 2016 10:54:00 GMT+0100 (CET)
Fired: Mon Feb 01 2016 10:55:00 GMT+0100 (CET)
```

**Comment by ekussberg** [comment] 2016-02-01 10:02
I see i found the issue of our problem:
https://github.com/node-schedule/node-schedule/issues/241

We have the same problem, that yesterday night was the last time cronjobs run and now they just even don't start when we restart our node instance.

Any suggestions?

**Comment by santigimeno** [comment] 2016-02-01 10:07
@ekussberg This: https://github.com/node-schedule/node-schedule/issues/225#issuecomment-177831888

**Comment by Alex777UAE** [comment] 2016-02-01 10:09
+1 cronjob doesn't run

**Comment by santigimeno** [comment] 2016-02-01 10:10
@Alex777UAE Any specifics? Have you applied the changes suggested in this thread?

**Comment by doronMendelson** [comment] 2016-02-01 10:13
@santigimeno 
I tried to run the same code you've added with the bugFixLeapYear code.
I've got the same error.

**Comment by santigimeno** [comment] 2016-02-01 10:14
@doronMendelson Have you run `npm install` after applying those changes so that `cron-parser` is updated?

**Comment by Alex777UAE** [comment] 2016-02-01 10:15
No, we didn't apply since development policy is not to install anything which might be lost after rm -rf node_modules/ && npm install

Can give you any details you need, currently it behave strange:
*/10 * * * * runs just after application startup (not multiple of 10 minutes) and then not repeat

**Comment by santigimeno** [comment] 2016-02-01 10:16
Ok, here's the plan. Unless the problem reported by  @holm reveals serious, or some other important issue arises, I'm going to release `1.0.0` this evening with the changes from https://github.com/node-schedule/node-schedule/pull/233. Thanks everyone

**Comment by santigimeno** [comment] 2016-02-01 10:17
@Alex777UAE I understand, but you can modify the package.json as suggested here: https://github.com/node-schedule/node-schedule/issues/225#issuecomment-177664035

**Comment by doronMendelson** [comment] 2016-02-01 10:17
@santigimeno It is working now. Thanks a lot

**Comment by santigimeno** [comment] 2016-02-01 10:18
@doronMendelson That's great news :)

**Comment by KevinC0** [comment] 2016-02-01 10:39
I have been using the @albertdatui branch for 11 hours now. I thought it tackled 100% of my issue, however, I discovered this morning a strange behavior every hour between :45 and :00. 

'var j = schedule.scheduleJob('*/2 * * * *', function(){'

https://www.dropbox.com/s/vxpy5die0btlqhc/Capture%20d%27%C3%A9cran%202016-02-01%2010.23.31.png?dl=0

I still have to investigate but it seems related.

**Comment by santigimeno** [comment] 2016-02-01 10:49
@KevinC0 Ok just let us know if you find something. FYI, I've run some tests with using your cron expression and `sinon` and it works correctly.

**Comment by zettam** [comment] 2016-02-01 11:03
Any solutions so far?

**Comment by holm** [comment] 2016-02-01 11:18
I have tried to reproduce the problem on my mac, but I can only reproduce on our servers. On our servers all the jobs fire immediately when started, and then never after that.

**Comment by santigimeno** [comment] 2016-02-01 11:25
@holm Thanks for the info. Can you reproduce it consistently on your servers? If that's the case, can you add these lines: 
```
  console.log('runOnDate >>>>>>>>>>>>>>>>>>>>>>>>>');
  console.log('now: ' + new Date(now));
  console.log('then: ' + new Date(then));
  console.log('runOnDate <<<<<<<<<<<<<<<<<<<<<<<<<');
```

To the `runOnDate` function here: https://github.com/albertdatui/node-schedule/blob/bugFixLeapYear/lib/schedule.js#L366, just before 
```
if (then < now) {
    process.nextTick(job);
    return null;
  }
```
And paste the output?

**Comment by holm** [comment] 2016-02-01 11:35
Alright, it seems the node-schedule package didn't update properly on the servers, even though the shrinkwrap file is fine and it works on Travis. I suspect it is a problem with npm@3.5, which has been giving us a bit of grief.

Sorry for the smoke on this, I think you should go ahead and release.

**Comment by santigimeno** [comment] 2016-02-01 11:42
@holm Thanks for the feedback! Regarding the `npm` issue. We have avoided upgrading to npm@3 because of some weird behaviour and are using npm@2 everywhere.

**Comment by santigimeno** [comment] 2016-02-01 11:46
Update regarding `1.0.0`. Here https://github.com/node-schedule/node-schedule/tree/v1.0-pre is the code I'll hopefully will be publishing this evening as `1.0.0`. It's just the code from https://github.com/node-schedule/node-schedule/pull/233 plus removing a functionality that was scheduled some time ago for `1.0.0`: https://github.com/node-schedule/node-schedule/issues/157. Any feedback would be appreciated. Thanks

**Comment by cybertim** [comment] 2016-02-01 15:12
It's working again, thank goodness :+1: 
```
wget https://github.com/node-schedule/node-schedule/archive/v1.0-pre.tar.gz
npm uninstall node-schedule
npm install v1.0-pre.tar.gz
```

**Comment by yossi-vexigo** [comment] 2016-02-01 15:23
+1

**Comment by GermanBluefox** [comment] 2016-02-01 15:55
```npm install https://github.com/node-schedule/node-schedule/tarball/v1.0-pre```

Works!

**Comment by Jean-PhilippeD** [comment] 2016-02-01 16:06
:+1:

**Comment by DefunctExodus** [comment] 2016-02-01 16:06
:+1: 

Thanks for the fix

**Comment by crissmoldovan** [comment] 2016-02-01 16:33
Thanks guys :)

**Comment by gruzilla** [comment] 2016-02-01 17:32
we changed our package.json to use the v1.0-pre repository and now everything works as it did 2015:

    "node-schedule": "node-schedule/node-schedule#v1.0-pre"

thanks for the fix! :+1:

**Comment by iwozzy** [comment] 2016-02-01 18:13
+1

**Comment by andrewpuch** [comment] 2016-02-01 18:28
+1

**Comment by ericsandine** [comment] 2016-02-01 18:40
:+1:  Looks like it's working here

**Comment by pgkehle** [comment] 2016-02-01 20:06
+1

**Comment by santigimeno** [comment] 2016-02-01 20:59
Fixed in 2468fb7 and released as version 1.0.0.
Major props to @albertdatui for the excellent fix.

**Closed by santigimeno** 2016-02-01 20:59 UTC
Labels: bug

**Comment by ryanprinsloo** [comment] 2016-02-02 05:31
Thanks for getting this sorted so quickly. You guys rock!

**Comment by mohitkhanna** [comment] 2016-02-02 08:06
+1

**Comment by NiViktor** [comment] 2016-02-02 08:15
Great work! Thanks!

**Comment by tejasmanohar** [comment] 2016-02-02 18:51
Good job @santigimeno @albertdatui

**Comment by corbanb** [comment] 2016-02-02 20:41
:+1:

**Comment by stephent** [comment] 2016-02-03 00:23
I updated to 1.0.0, deployed and restarted my app, but my scheduled jobs are no longer firing (last execution was at 09:00 Jan 31 (Mountain Time). The schedule is as follows:

`var job = schedule.scheduleJob('0 0,4,8,12,16,20 * * *', function(){...});`

Is there something else I need to do to get things running again? Thanks!
