### ISSUE TITLE
CancelNext does not reschedule later invocations when using a cron expression

### ISSUE THREAD

**Issue by hgrubst** [node-schedule/node-schedule#341] opened 2017-04-17 01:56 UTC
I was expecting the following code to cancel one invocation but it is actually cancelling them all : 
```javascript
let schedule = require('node-schedule');

var j = schedule.scheduleJob('*/1 * * * * *', function(){
  console.log('Job every 1 seconds');
});

console.log(j.pendingInvocations().length) // prints 1
console.log(j.nextInvocation().toString()) //prints date in 1 sec

j.cancelNext(true);

console.log(j.pendingInvocations().length) //prints 0
console.log(j.nextInvocation().toString()) //error as nextInvocation is null
```

The cancelNext function is looking for a recurs field on the recurrenceRule which is not present when using a cron expression :
```javascript
this.cancelNext = function(reschedule) {
...
if (reschedule && nextInv.recurrenceRule.recurs) {
      newInv = scheduleNextRecurrence(nextInv.recurrenceRule, this, nextInv.fireDate, nextInv.endDate);
      if (newInv !== null) {
        this.trackInvocation(newInv);
      }
 }
...
}
```
Is this intentional and means you can only cancel jobs when using the RecurrenceRules API ?

**Comment by santigimeno** [comment] 2017-04-23 10:43
@hgrubst thanks for the report. I think you've found a bug. Any cron job is by definition recursive and should work in the same way as RecurrenceRules. Can you check if this patch fixes the issue for you?

```js
diff --git a/lib/schedule.js b/lib/schedule.js
index 835540b..f7585fc 100644
--- a/lib/schedule.js
+++ b/lib/schedule.js
@@ -89,7 +89,8 @@ function Job(name, job, callback) {
 
       cancelInvocation(inv);
 
-      if (reschedule && inv.recurrenceRule.recurs) {
+      if (reschedule && (nextInv.recurrenceRule.recurs ||
+                         nextInv.recurrenceRule.next)) {
         newInv = scheduleNextRecurrence(inv.recurrenceRule, this, inv.fireDate, inv.endDate);
         if (newInv !== null) {
           newInvs.push(newInv);
@@ -124,7 +125,8 @@ function Job(name, job, callback) {
 
     cancelInvocation(nextInv);
 
-    if (reschedule && nextInv.recurrenceRule.recurs) {
+    if (reschedule && (nextInv.recurrenceRule.recurs ||
+                       nextInv.recurrenceRule.next)) {
       newInv = scheduleNextRecurrence(nextInv.recurrenceRule, this, nextInv.fireDate, nextInv.endDate);
       if (newInv !== null) {
         this.trackInvocation(newInv);
```

**Comment by santigimeno** [comment] 2017-11-14 18:30
@hgrubst ping

**Comment by joshmeads** [comment] 2019-02-01 22:57
@santigimeno I can confirm this patch fixes the issue. The issue is still ongoing and this would be a great fix to get merged in.

**Closed** 2019-02-06 20:22 UTC
