### ISSUE TITLE
Recurring jobs trigger by an offset

### ISSUE THREAD

**Issue by sebastiaanluca** [node-schedule/node-schedule#218] opened 2015-12-06 14:06 UTC
So I've been having some troubles scheduling jobs correctly. I made an alarm clock and have 2 recurring jobs scheduled. The main alarm at 8:00 every day, the other to snooze the alarm at about 9:00.

Problem is that the first run goes well, but the second day the script has been running, only my snooze job triggers. I thought my snooze job was overriding the alarm or the alarm somehow used the snooze settings, but now I'm thinking it's more that one or both don't get triggered or get triggered at the wrong time. Maybe because it's a long-running script and the internal timers get messed up?

I've tested it with hourly jobs:

```
var alarmJob = Schedule.scheduleJob({minute: 0}, onAlarmTriggerHandler);
var fixedSnoozeJob = Schedule.scheduleJob({minute: 20}, onFixedSnoozeTriggerHandler);
```

First run goes well:
```
Alarm triggered! It is now December 6th 2015, 1:00:00 pm
Force-snoozing alarm. Stopping playback. It is now December 6th 2015, 1:20:00 pm
```

Script kept running for the next hour:
```
Alarm triggered! It is now December 6th 2015, 2:01:07 pm
Force-snoozing alarm. Stopping playback. It is now December 6th 2015, 2:20:00 pm
```

You see the alarm job is starting to offset. When I'd use daily settings, I think it gets shifted even more. Only my snooze seems to trigger correctly every day, but the alarm itself never gets executed after the first day.

Any thoughts on this? If I can debug this even better, let me know.

**Comment by sebastiaanluca** [comment] 2015-12-06 15:06
I think my hunch was right. Hour 3:
```
Alarm triggered! It is now December 6th 2015, 3:56:51 pm +1h
Force-snoozing alarm. Stopping playback. It is now December 6th 2015, 3:56:51 pm +109ms
```

So first run is ok, second run offset by about a minute, third run by almost 7 minutes. By that time, the alarm and the snooze job get triggered at the same time. Any later and the alarm job will be ignored completely.

Going to try to schedule jobs and reschedule them on completion as a temporary workaround. Thought you should know about this issue though.

**Comment by santigimeno** [comment] 2015-12-06 18:12
@sebastiaanluca That's weird. I can't reproduce it using `sinon fakeTimers`. I'm now running a test with ordinary timers to see if there's any difference. One question: are your running the program in a computer that occasionally suspends? That could cause problems. See: https://github.com/node-schedule/node-schedule/issues/96

**Comment by sebastiaanluca** [comment] 2015-12-06 18:15
@santigimeno Nope, running it on an original Raspberry Pi. The jobs for hours 4 and 5 didn't run, but then at 6pm, it suddenly did again. Not sure if it's my code or what. Just setting up 2 jobs (alarm + snooze) and setting up a third (cron job) in the alarm job that quits after a minute or five.

```
Schedule.scheduleJob('*/' + (60 / increaseSteps) + ' * * * * *', onIncreaseVolumeTriggerHandler);
```

**Comment by santigimeno** [comment] 2015-12-06 18:24
@sebastiaanluca please, can you paste a complete I can test?

**Comment by santigimeno** [comment] 2015-12-06 18:53
I meant a complete program

**Comment by tejasmanohar** [comment] 2015-12-06 19:43
(simple example that demonstrates this error so it can be reproduced locally)

**Comment by sebastiaanluca** [comment] 2015-12-06 20:47
This is the module that's using the jobs: https://github.com/sebastiaanluca/alarmclock/blob/feature/controls/pigpio/src/modules/SebastiaanLuca/AlarmClock/src/AlarmClock.js and the fix (creating new jobs instead of using recurring ones) that works neither: https://github.com/sebastiaanluca/alarmclock/blob/feature/alarm/fix-schedules/src/modules/SebastiaanLuca/AlarmClock/src/AlarmClock.js.

See https://gist.github.com/sebastiaanluca/b8edac61b693d3db2f23 for a short example. I'm letting it run overnight to see what kind of results it gives. Problem debugging this issue is that it has to run every hour or every day (to magnify the offset in the results).

Just wondering though: do I have to keep a reference to the job somewhere in my global app so it won't get garbage collected? I don't know if that's even the case in JS, but I had an alarm set for 21:30 and it didn't get triggered either, only the first 2 runs at 7:30 and 8:30.

**Comment by sebastiaanluca** [comment] 2015-12-07 13:39
```
var Schedule = require('node-schedule');

//

// Schedule the jobs
console.log('Setting up jobs');

var alarmRule = new Schedule.RecurrenceRule();
alarmRule.hour = null;
alarmRule.minute = 20;
alarmRule.second = 0;

Schedule.scheduleJob(alarmRule, function () {
    console.log('[ALARM1] Alarm triggered! It is now %s', (new Date()));
});

//

console.log('BOOTED');
```

Very simple example that only runs once when it should run every hour, right?

**Comment by santigimeno** [comment] 2015-12-07 16:01
@sebastiaanluca I've been running the code you pasted for a couple of hours and worked fine. See:
```
Setting up jobs
BOOTED
[ALARM1] Alarm triggered! It is now Mon Dec 07 2015 15:20:00 GMT+0100 (CET)
[ALARM1] Alarm triggered! It is now Mon Dec 07 2015 16:20:00 GMT+0100 (CET)
```
What output would you expect?

**Comment by sebastiaanluca** [comment] 2015-12-07 16:19
@santigimeno The same as yours, a trigger every hour, but it's not working here :s Can this be environment-related? How do I debug this?

**Comment by santigimeno** [comment] 2015-12-07 16:22
Probably. Have you tried running one hour long timeouts  and intervals and see how it goes?

**Comment by sebastiaanluca** [comment] 2015-12-07 16:23
Do you have some example code for that? JS is not my strong suit.

**Comment by sebastiaanluca** [comment] 2015-12-09 13:31
```js
console.log('Setting up interval to run every 30 minutes');

setInterval(function () {
    console.log('Interval trigger! It is now %s', (new Date()));
}, 1000 * 60 * 30);
```

Lol, why isn't this working? :s Every minute works just fine. Every 30 or 60 fails.

**Comment by tejasmanohar** [comment] 2015-12-09 18:21
Should work, @sebastiaanluca. Are you starting / stopping the script, or is your system/process sleeping or anything like that? Remember, setInterval alone provides no persistence on the jobs.

**Comment by sebastiaanluca** [comment] 2015-12-09 21:04
@tejasmanohar I'm starting it using `node src/tests/job12.js` for instance, pretty basic I guess? How can I check if the process is sleeping or how would I prevent that? My Pi is always on. I tried running the same script with a 20-minute interval alongside the 60-minute interval and the 20-minute interval works just fine. I can't find any related situations on Google either. It's always in the browser, not using NodeJS.

**Comment by sebastiaanluca** [comment] 2015-12-10 19:14
It only works when I also set a shorter interval, like so:
```js
console.log('Setting up a 20 and 60-minute interval. It is now %s', (new Date()));

setInterval(function () {
    console.log('20-minute interval trigger! It is now %s', (new Date()));
}, 1000 * 60 * 20);

setInterval(function () {
    console.log('60-minute interval trigger! It is now %s', (new Date()));
}, 1000 * 60 * 60);

console.log('BOOTED');
```

The 60-minute interval on its own (with the 20-minute interval) does not trigger.

**Comment by tejasmanohar** [comment] 2016-02-01 08:07
>I tried running the same script with a 20-minute interval alongside the 60-minute interval and the 20-minute interval works just fine. I can't find any related situations on Google either. It's always in the browser, not using NodeJS.
Maybe your browser has some timeouts, not sure. Why not try it with a process in Node? Anyways, happy to continue the discussion here, but since this doesn't work w/ setTimeout either on your setup, it's not an issue w/ this module so closing.

**Closed by tejasmanohar** 2016-02-01 08:07 UTC

**Comment by sebastiaanluca** [comment] 2016-02-01 08:18
> Maybe your browser has some timeouts, not sure. Why not try it with a process in Node? Anyways, happy to continue the discussion here, but since this doesn't work w/ setTimeout either on your setup, it's not an issue w/ this module so closing.

I meant the issues are always browser-related, not in the command-line. I'm always using the CLI. But you're right, it's a `setTimeOut` issue and thus won't work if your package depends on it. Thanks anyway!
