### ISSUE TITLE
RecurrenceRule "date" does not work

### ISSUE THREAD

**Issue by alexgleason** [node-schedule/node-schedule#353] opened 2017-05-24 00:35 UTC
I expect the following to run only on the first day of each month since `"date": 1`, but instead of would run every single day.

```javascript
schedule.scheduleJob({ "date": 1, "hour": 6, "minute": 30 }, cb);
```

I'm now testing out the following. Hopefully this does what I want.

```javascript
schedule.scheduleJob("30 6 1 * *", cb);
```

**Comment by rynobax** [comment] 2017-05-24 20:40
The test below did not fail when I ran it, so I am unsure of how to reproduce the issue.
```javascript
"Test": function(test) {
    let counter = 0;

    schedule.scheduleJob({ "date": 1, "hour": 6, "minute": 30 }, () => {
        // Should count 3 times in 65 days
        counter++;
    });

    const days = 65;
    const msInDay = 1000 * 60 * 60 * 24;
    clock.tick(msInDay * days);

    test.equal(counter, 3);
    test.done();
}
```

**Comment by alexgleason** [comment] 2017-05-24 21:37
Thank you for checking. You can view the full code here to see the context. https://github.com/Uptwinkles/twink/blob/e80d26effe10e3adc48b033280d9b1a47a720e1d/app/server.js#L136

I deployed the change to a cron string this morning so I'll see tomorrow if we're still getting the other error.

Thanks!

**Comment by alexgleason** [comment] 2017-06-01 15:17
I've just confirmed,

* With `date` set to `1` it **did not work as intended.** It ran every day.
* With a cron string set to `30 6 1 * *` it **worked**. Today I got the notification, but yesterday and the day before I did not. Today is the first of the month, and the other days were not.
* No other code was changed between these two tests.

You can see in Uptwinkles/twink@e80d26effe10e3adc48b033280d9b1a47a720e1d that we set the parameters correctly (I hope). It still didn't work right.

Then in Uptwinkles/twink@896c789ff5fa6f1ce70c0192412024d313ec58c6 we used a cron string instead, and this worked perfectly.

**Comment by santigimeno** [comment] 2017-06-13 17:52
Unfortunately cannot reproduce it either neither with version `1.2.1` nor `1.2.3`.

**Comment by alexgleason** [comment] 2017-06-13 17:58
That is really strange. Did you let it run overnight to rule out errors in testing tools? It's totally possible there's something else going on here, but it was pretty clear that changing to a cron string fixed it.

**Comment by santigimeno** [comment] 2017-06-13 18:09
Just tested with `sinon` `fakeTimers`. I can do it without it but can you provide more specifics on how it fails? Does it always fail from the start (from day one) or have to wait some months for it to happen?

**Comment by alexgleason** [comment] 2017-06-13 18:12
It always fails from the start. We had this in operation for multiple days, and each day it would trigger the job despite having `date` set. For instance, `{ "date": 1, "hour": 6, "minute": 30 }` would trigger on the 15th at 6:30, the 16th at 6:30, the 17th at 6:30... and so on.

**Comment by santigimeno** [comment] 2017-06-13 18:13
The code I'm using is this:
```js
'use strict';

const schedule = require('./');
const now = Date.now();
const clock = require('sinon').useFakeTimers();
	
clock.tick(now);

console.log('Starting the Job: ', (new Date()).toString());

schedule.scheduleJob({ "date": 1, "hour": 6, "minute": 30 }, () => {
  console.log('Job fired!', (new Date()).toString());
});

const days = 935;
const msInDay = 1000 * 60 * 60 * 24;
clock.tick(msInDay * days);
```

The output looks like this
```
Starting the Job:  Tue Jun 13 2017 20:13:10 GMT+0200 (CEST)
Job fired! Sat Jul 01 2017 06:30:00 GMT+0200 (CEST)
Job fired! Tue Aug 01 2017 06:30:00 GMT+0200 (CEST)
Job fired! Fri Sep 01 2017 06:30:00 GMT+0200 (CEST)
Job fired! Sun Oct 01 2017 06:30:00 GMT+0200 (CEST)
Job fired! Wed Nov 01 2017 06:30:00 GMT+0100 (CET)
Job fired! Fri Dec 01 2017 06:30:00 GMT+0100 (CET)
Job fired! Mon Jan 01 2018 06:30:00 GMT+0100 (CET)
Job fired! Thu Feb 01 2018 06:30:00 GMT+0100 (CET)
Job fired! Thu Mar 01 2018 06:30:00 GMT+0100 (CET)
Job fired! Sun Apr 01 2018 06:30:00 GMT+0200 (CEST)
Job fired! Tue May 01 2018 06:30:00 GMT+0200 (CEST)
Job fired! Fri Jun 01 2018 06:30:00 GMT+0200 (CEST)
Job fired! Sun Jul 01 2018 06:30:00 GMT+0200 (CEST)
Job fired! Wed Aug 01 2018 06:30:00 GMT+0200 (CEST)
Job fired! Sat Sep 01 2018 06:30:00 GMT+0200 (CEST)
Job fired! Mon Oct 01 2018 06:30:00 GMT+0200 (CEST)
Job fired! Thu Nov 01 2018 06:30:00 GMT+0100 (CET)
Job fired! Sat Dec 01 2018 06:30:00 GMT+0100 (CET)
Job fired! Tue Jan 01 2019 06:30:00 GMT+0100 (CET)
Job fired! Fri Feb 01 2019 06:30:00 GMT+0100 (CET)
Job fired! Fri Mar 01 2019 06:30:00 GMT+0100 (CET)
Job fired! Mon Apr 01 2019 06:30:00 GMT+0200 (CEST)
Job fired! Wed May 01 2019 06:30:00 GMT+0200 (CEST)
Job fired! Sat Jun 01 2019 06:30:00 GMT+0200 (CEST)
Job fired! Mon Jul 01 2019 06:30:00 GMT+0200 (CEST)
Job fired! Thu Aug 01 2019 06:30:00 GMT+0200 (CEST)
Job fired! Sun Sep 01 2019 06:30:00 GMT+0200 (CEST)
Job fired! Tue Oct 01 2019 06:30:00 GMT+0200 (CEST)
Job fired! Fri Nov 01 2019 06:30:00 GMT+0100 (CET)
Job fired! Sun Dec 01 2019 06:30:00 GMT+0100 (CET)
Job fired! Wed Jan 01 2020 06:30:00 GMT+0100 (CET)
```

**Comment by santigimeno** [comment] 2017-06-13 18:14
Ok. I'll let the sample code running for a couple of days without the `sinon.fakeTimer`. Let's see how it goes.

**Comment by santigimeno** [comment] 2017-06-16 09:02
@alexgleason had the test running for almost three days and, unfortunately couldn't reproduce the issue :(

**Comment by santigimeno** [comment] 2017-11-14 18:23
Closing it. Feel free to reopen if you can provide some more info about how to reproduce the issue. Thanks

**Closed by santigimeno** 2017-11-14 18:23 UTC

**Comment by alexgleason** [comment] 2017-11-14 18:29
Thanks for your efforts on this. Really strange issue. The cron string worked fine so we're happy. Still, very unusual.
