### ISSUE TITLE
Install warnings

### ISSUE THREAD

**Issue by anthonywebb** [node-schedule/node-schedule#312] opened 2016-11-29 01:00 UTC
Running node 6.3 and when installing I am seeing the following warnings:

MacBook-Pro-2:player-rpi webb$ npm install node-schedule -save
(node:93859) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
(node:93859) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
(node:93859) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
(node:93859) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
(node:93859) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
(node:93859) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
(node:93859) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
(node:93859) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
(node:93859) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
ScreenyRPI@0.0.1 /Users/webb/projects/tt-screen/player-rpi
└─┬ node-schedule@1.2.0 
  ├── cron-parser@1.1.0 
  └── long-timeout@0.0.2

**Comment by anthonywebb** [comment] 2016-11-29 03:04
Note that when I installed using node 7.2 I did not get any of the warnings

**Comment by santigimeno** [comment] 2017-01-12 21:48
I can't reproduce it locally:
```
/tmp]$ node -v
v6.3.0
 /tmp]$ npm i node-schedule
/private/tmp
└─┬ node-schedule@1.2.0 
  ├── cron-parser@1.1.0 
  └── long-timeout@0.0.2 

npm WARN enoent ENOENT: no such file or directory, open '/private/tmp/package.json'
npm WARN tmp No description
npm WARN tmp No repository field.
npm WARN tmp No README data
npm WARN tmp No license field.
```
are you sure it's not a problem with another module you have in your node_modules directory? I say this because `node-schedule` does not use `graceful-fs`.

**Comment by santigimeno** [comment] 2017-05-02 16:19
No follow-up. Closing. Feel free to re-open if this is still an issue. Thanks

**Closed by santigimeno** 2017-05-02 16:19 UTC
